# math module
- The math module gives access to the underlying C library functions for floating point math:
- https://www.w3schools.com/python/module_math.asp

In [22]:
import math  # import whole module

In [34]:
number = 7/-3
print(number)
print(round(number))         # round down
print(round(number, 2))     # decimal with two decimal digits 
print(abs(number))              # absolute
print(bin(2))                          # binary of -2

-2.3333333333333335
-2
-2.33
2.3333333333333335
0b10


In [25]:
print(math.ceil(3.4))  # round float upward
print(math.floor(3.2))  # round downward

4
3


In [36]:
print(math.copysign(2, -4)) # Return a float with the magnitude (absolute value) of x but the sign of y.
print(math.pi)
print(math.cos(math.pi))
print(math.log(1024, 2))
print(complex(3, 5))  # complex number

-2.0
3.141592653589793
-1.0
10.0
(3+5j)


In [23]:
x = [3,4,5]
math.prod(x, start=3)    # 3*3*4*5 = 180

180

In [24]:
y = [1,45,34,2,5,6,7,8,21,3,4,78,999]
sorted(y)

[1, 2, 3, 4, 5, 6, 7, 8, 21, 34, 45, 78, 999]

In [26]:
math.comb(5,2)           # combinatons - draw k out of  n, while arrangement doesn't count
math.factorial(5)          # factorial - Fakultät
math.fabs(-1.234)        # absolute

1.234

In [ ]:
# see all functions 
help("math")

Help on module math:

NAME
    math

MODULE REFERENCE
    https://docs.python.org/3.8/library/math
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
    

# random
https://www.w3schools.com/python/module_random.asp

In [ ]:
import random
print(random.choice(['apple', 'pear', 'banana']))   # chooses one
print(random.sample(range(100), 10))                    # sampling without replacement
print(random.random())                                             # random float
print(random.randrange(6))                                       # choice between 0 and 5
print(random.randrange(2,8))                                   # choice between 2 and 7


banana
[9, 27, 6, 47, 26, 98, 25, 4, 64, 37]
0.4262600099790683
1
2


In [ ]:
#Same thing as above using numpy would be
from numpy import random
random.sample()

0.7272043691533635

In [ ]:
# x% quantile, percentage point is the cutoff value that has x% of the distribution to the left of it
print(stats.norm.ppf(q=0.75))

0.6744897501960817


In [ ]:
# random numbers from a normal distribution of a particular mean and standard deviation
# mean, std, size
np.random.normal(1, 2, (3,2))

array([[-2.97158887,  0.32875287],
       [ 2.45125776,  1.82765682],
       [-1.56081246, -2.10099321]])

In [ ]:
# random numbers from a normal distribution between 0 and 1
# row, col
np.random.rand(3, 2)

array([[0.85567439, 0.82840517],
       [0.39355712, 0.76113585],
       [0.52102372, 0.60167845]])

In [ ]:
# random numbers from a standard normal distribution
# This is a special case 'randn'  of the normal distribution when μ = 0  and σ = 1
np.random.randn(3, 2)

array([[ 0.10697596,  0.23867035],
       [-1.66626204, -1.96403154],
       [-2.10682777, -0.7897286 ]])

# Measures of Central Tendency

In [ ]:
# Measures of Central Tendency
import statistics as stat
import random
d = random.sample(range(500), 200)
stat.mean(d)
stat.mode(d)
stat.multimode([2, 3, 4, 2])
stat.median(d)                         # Calculates the median (middle value) of the given data
stat.median_grouped(d)         # Calculates the median of grouped continuous data
stat.median_high(d)
stat.median_low(d)
stat.variance(d)                      # Calculates the variance from a sample of data
stat.pvariance() 	              # Calculates the variance of an entire population
stat.stdev(d)                           # Calculates the standard deviation from a sample of data
stat.pstdev(d) 	                # Calculates the standard deviation from an entire population

[2]

## basic statistics in pandas

In [ ]:
import pandas as pd 
food = pd.read_csv('fao_food_prices.csv', header=2)
food.drop(axis=0, index=0, inplace=True)
food['Date'] = pd.to_datetime(food['Date'])
food.set_index("Date", inplace=True)
food.dropna(inplace=True)

In [ ]:
food.count() 	       # Number of non-null observations
food.sum() 	            # Sum of values
food.mean() 	      # Mean of Values
food.median() 	
food.mode() 	
food.std() 	
food.min() 	
food.max() 	
food.abs() 	
food.prod() 	
food.cumsum() 	
food.cumprod() 	

In [ ]:
food.describe(include='all')

Food Price Index        Meat       Dairy     Cereals        Oils  \
count        384.000000  384.000000  384.000000  384.000000  384.000000   
mean          83.911979   83.151302   82.570573   84.989323   86.248750   
std           24.406812   16.214462   31.895191   29.689929   34.284582   
min           50.500000   51.100000   36.800000   48.600000   35.830000   
25%           63.650000   70.550000   54.825000   59.975000   61.797500   
50%           78.000000   81.650000   75.600000   80.350000   79.950000   
75%           98.825000   96.175000  107.550000  100.725000  103.835000   
max          137.600000  119.200000  156.500000  163.300000  184.840000   

            Sugar  
count  384.000000  
mean    80.233594  
std     31.093586  
min     31.800000  
25%     57.575000  
50%     74.750000  
75%     95.675000  
max    183.200000

# selfmade statsistic functions 

## Arithmetic mean
${\displaystyle A={\frac {1}{n}}\sum _{i=1}^{n}a_{i}={\frac {a_{1}+a_{2}+\cdots +a_{n}}{n}}}$

In [ ]:
def my_amean (num: list) -> float:
    sum = 0
    for numbers in num:
        sum += numbers
    amean = sum / len(num)
    return amean

my_amean([3,5,6,9])

5.75

## Median
The median $\tilde x$ is the value separating the higher half from the lower half of a data sample.<br>
For a data set, it may be thought of as "the middle" value. 

The basic feature of the median in describing data compared to the mean $\overline x$ is that it is not skewed by a small proportion of extremely large or small values, and therefore provides a better representation of a "typical" value. 

The median is of central importance in **robust** statistics, as it is the **most resistant statistic**, having a breakdown point of 50%: so long as no more than half the data are contaminated, the median is not an arbitrarily large or small result. 

$\tilde x
=\begin{cases}
  x_{m+1}                     & \text { for odd n = 2m+1}\\
  \frac{1}{2} (x_m + x_{m+1}) & \text { for even n = 2m}
\end{cases}
$

In [ ]:
def my_median (num: list) -> float:
    '''number that resides in the middle of a sorted list of  numbers'''
    ls = sorted(num)
    lg = len(num)
    m = lg/2
    if lg%2 == 1:
        med = ls[int(m)]
    else:
        med = (ls[int(m-1)]+ls[int(m)])/2
    return med

my_median([10,17,20, 22, 25, 34, 37, 48, 59])

25

## Mode

In [ ]:
def my_mode(ls):
    ''' mode that allows for more than one mode value'''
    # count - counts elements in an iterable
    # map - goes ove every element in iterable
    # filter - picks items for wich the filter criteria is true
    most = max(list(map(ls.count, ls)))
    return list(set(filter(lambda x: ls.count(x) == most, ls)))

my_mode([2,3,5, 5, 5, 2, 3, 8])
my_mode([1, 2, 2, 3, 3])


[2, 3]

In [ ]:
def my_modus(num: list) -> float:
    ''' mode that allows for more than one mode value'''
    freq = {}                             # build a dict, that lists the existing vakues and their frequencies
    for x in num:
        h = num.count(x)          # count frequency of value x
        freq[x] = h                     # add value x and it's frequency to the dict

    value_list = list(freq.values())    # make two lists of the same lenght out of
    key_list = list(freq.keys())          # dictionaries keys and values

    maximum = 0                         # find max frequency
    for y in value_list:
        if  y > maximum:
            maximum = y

    position = value_list.index(maximum)    # take position of max frequency to extract corresponding key
    return key_list[position]


my_modus([1, 2, 3])
my_mode([1, 2, 2, 3, 3])


[2, 3]

## Geometric Mean
$\left(\prod _{i=1}^{n}x_{i}\right)^{\frac {1}{n}}={\sqrt[{n}]{x_{1}x_{2}\cdots x_{n}}}$

In [ ]:
def my_geomean(ls: list) -> float:
    '''mean or average, which indicates the central tendency or 
    typical value of a set of numbers by using the product of their value'''
    growthfactors = []

    for index in range(1, len(ls)):          # range fct spits out the indexes
        g_fact = ls[index]/ls[index-1]
        growthfactors.append(g_fact)         # create a list

    prod = 1                                 # product of list instead of product()
    for fact in  growthfactors:
        prod *= fact

    geo_mean = prod**(1/2)
    return geo_mean


my_geomean([2, 3, 5, 5, 5, 2, 3, 8])


2.0

## Harmonic Mean
$\frac {n}{\frac{1}{x_1}+\frac{1}{x_2}+\frac{1}{x_3}+…+\frac{1}{x_n}}$

In [ ]:
def my_harmonic_mean(ls: list) -> float:
    sum = 0
    for x in ls:
        sum += 1/x
    mean = sum / len(ls)
    hmean = 1/mean
    return hmean

In [ ]:
# growth = (100, 103, 104, 134, 145)
# print(my_harmonic_mean(growth))

# statistic module
https://www.w3schools.com/python/module_statistics.asp

In [40]:
import statistics
data = [2.75, 1.75, 1.25, 0.25, 0.5, 1.25, 3.5]
print(statistics.mean(data))
print(statistics.median(data))
print(statistics.variance(data))


1.6071428571428572
1.25
1.3720238095238095


In [43]:
help(statistics)
dir(statistics)

Help on module statistics:

NAME
    statistics - Basic statistics module.

MODULE REFERENCE
    https://docs.python.org/3.8/library/statistics
    
    The following documentation is automatically generated from the Python
    source files.  It may be incomplete, incorrect or include features that
    are considered implementation detail and may vary between Python
    implementations.  When in doubt, consult the module reference at the
    location listed above.

DESCRIPTION
    This module provides functions for calculating statistics of data, including
    averages, variance, and standard deviation.
    
    Calculating averages
    --------------------
    
    ==================  ==================================================
    Function            Description
    ==================  ==================================================
    mean                Arithmetic mean (average) of data.
    fmean               Fast, floating point arithmetic mean.
    geometric_mean    

['Counter',
 'Decimal',
 'Fraction',
 'NormalDist',
 'StatisticsError',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_coerce',
 '_convert',
 '_exact_ratio',
 '_fail_neg',
 '_find_lteq',
 '_find_rteq',
 '_isfinite',
 '_normal_dist_inv_cdf',
 '_ss',
 '_sum',
 'bisect_left',
 'bisect_right',
 'erf',
 'exp',
 'fabs',
 'fmean',
 'fsum',
 'geometric_mean',
 'groupby',
 'harmonic_mean',
 'hypot',
 'itemgetter',
 'log',
 'math',
 'mean',
 'median',
 'median_grouped',
 'median_high',
 'median_low',
 'mode',
 'multimode',
 'numbers',
 'pstdev',
 'pvariance',
 'quantiles',
 'random',
 'sqrt',
 'stdev',
 'tau',
 'variance']